[package]
name = "dist-intro"
version = "0.1.0"
authors = ["xushanpu123 <798304030@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
